enable_dr: false

vpc_cidr_blocks:
  us-east-1:
    dev: {{ dev_network_range }}
    stg: {{ stage_network_range }}
    # uat: 172.17.144.0/21
    # prd: 172.17.152.0/21
  us-west-2:
    # uat: 172.17.176.0/21
    # prd: 172.17.184.0/21